(add-to-list 'load-path (file-name-directory (or load-file-name buffer-file-name)))
(require 'tne-model)(require 'tne-render)
(defvar tne-mode-map (let ((m (make-sparse-keymap)))
 (define-key m (kbd "C-c C-2 a") #'tne-add-n2-segment)
 (define-key m (kbd "C-c C-3 a") #'tne-add-n3-segment)
 (define-key m (kbd "C-c C-r") #'tne-redraw) m))
(defun tne-redraw () (interactive)
 (let ((inhibit-read-only t))
  (erase-buffer)
  (insert (tne-document-narrative-1 tne-current-document) "\n")
  (insert (tne-render-segments (tne-document-n2-segments tne-current-document)) "\n")
  (insert (tne-render-segments (tne-document-n3-segments tne-current-document)) "\n")))
(defun tne-add-segment (n)
 (let ((c (read-number "Start column: ")) (txt (read-string "Segment text: ")))
  (let ((s (make-tne-segment :start-column c :text txt)))
   (if (= n 2)
    (setf (tne-document-n2-segments tne-current-document) (cons s (tne-document-n2-segments tne-current-document)))
    (setf (tne-document-n3-segments tne-current-document) (cons s (tne-document-n3-segments tne-current-document)))))
  (tne-redraw)))
(defun tne-add-n2-segment()(interactive)(tne-add-segment 2))
(defun tne-add-n3-segment()(interactive)(tne-add-segment 3))
(define-derived-mode tne-mode special-mode "TNE"
 (setq tne-current-document (tne-model-create-default))
 (setq buffer-read-only nil)(tne-redraw))
(provide 'tne-mode)
