(require 'tne-model)
(defun tne-render-segments (segments)
 (let ((line ""))
  (dolist (s (sort (copy-sequence segments)
   (lambda (a b) (< (tne-segment-start-column a) (tne-segment-start-column b)))))
   (while (< (length line) (tne-segment-start-column s)) (setq line (concat line " ")))
   (setq line (concat line (tne-segment-text s))))
  line))
(provide 'tne-render)
