(require 'cl-lib)
(cl-defstruct tne-segment start-column text)
(cl-defstruct tne-document (narrative-1 "") (n2-segments nil) (n3-segments nil))
(defvar-local tne-current-document nil)
(defun tne-model-create-default () (make-tne-document :narrative-1 "Narrative 1"))
(provide 'tne-model)
